In [96]:
import numpy as np
import time

def findLatin(size_mat, verbose = False):
    t = time.time()
    while(True):
        condition_orderings = []
        for _ in range(5):
            condition_orderings.append(np.random.permutation(5))
        condition_orderings = np.asarray(condition_orderings) + 1
    #     print(condition_orderings)

        # check if it is a Latin Square
        isLatin = True
        for ci in range(condition_orderings.shape[1]):
            values, counts = np.unique(condition_orderings[:,ci], return_counts = True)
    #         print(counts)
    #         print(np.unique(counts))
            if verbose:
                if len(np.unique(counts)) == 1:
                    print('hope!')
                if len(np.unique(counts)) != 1:
                    print('------------fail-----------' + str(ci))

            if len(np.unique(counts)) != 1:
                isLatin = False
                break

        if isLatin:
            if verbose:
                print('Took ' + str(time.time() - t) + ' sec to find a Latin square matrix.')
            break
    return condition_orderings

c1 = findLatin(5)
c2 = findLatin(5)

print(c1)
print(c2)

[[5 4 2 1 3]
 [3 5 4 2 1]
 [1 2 3 4 5]
 [2 3 1 5 4]
 [4 1 5 3 2]]
[[3 4 2 5 1]
 [5 1 3 4 2]
 [2 3 5 1 4]
 [4 2 1 3 5]
 [1 5 4 2 3]]


In [97]:
c1

array([[5, 4, 2, 1, 3],
       [3, 5, 4, 2, 1],
       [1, 2, 3, 4, 5],
       [2, 3, 1, 5, 4],
       [4, 1, 5, 3, 2]])